# Generated by Django 6.1 on 2026-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chit',
            name='chits_chit_priorit_6060fa_idx',
        ),
        migrations.AddField(
            model_name='chit',
            name='is_via_eb',
            field=models.BooleanField(default=False, help_text="Delegate-to-delegate chit CC'd to the committee's Executive Board. Meaningless (and always False) for chits already addressed directly to the Executive Board."),
        ),
        migrations.RemoveField(
            model_name='chit',
            name='priority',
        ),
    ]
