# Generated by Django 6.1 on 2026-08-17 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone name, e.g. Asia/Kolkata', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('chit_submissions_enabled', models.BooleanField(default=True)),
                ('delegate_to_eb_enabled', models.BooleanField(default=True)),
                ('anonymous_chits_enabled', models.BooleanField(default=False)),
                ('replies_enabled', models.BooleanField(default=True)),
                ('cross_committee_chits_enabled', models.BooleanField(default=False)),
                ('max_message_length', models.PositiveIntegerField(default=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='conference_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conferences.conference')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('conference', 'name')},
            },
        ),
    ]
