# Generated by Django 6.1 on 2026-08-17 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('committee_type', models.CharField(choices=[('general_assembly', 'General Assembly'), ('security_council', 'Security Council'), ('ecosoc', 'ECOSOC'), ('crisis', 'Crisis Committee'), ('specialized_agency', 'Specialized Agency'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_cross_committee_chits', models.BooleanField(default=False, help_text='If enabled (and conference allows it), delegates here may message other committees.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='conferences.conference')),
                ('room', models.ForeignKey(blank=True, help_text="The committee's assigned room. Auto-attached to every chit sent from this committee.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='conferences.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('vice_chair', 'Vice Chair'), ('director', 'Director'), ('rapporteur', 'Rapporteur'), ('moderator', 'Moderator')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committee', 'role'],
            },
        ),
        migrations.CreateModel(
            name='CountryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=150)),
                ('country_code', models.CharField(help_text='ISO-like short code, e.g. IND, USA', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_assignments', to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committee', 'country_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='committee',
            constraint=models.UniqueConstraint(fields=('conference', 'name'), name='unique_committee_name_per_conference'),
        ),
        migrations.AddIndex(
            model_name='committeestaff',
            index=models.Index(fields=['committee', 'is_active'], name='committees__committ_a5e15d_idx'),
        ),
        migrations.AddConstraint(
            model_name='committeestaff',
            constraint=models.UniqueConstraint(fields=('user', 'committee'), name='unique_staff_per_user_per_committee'),
        ),
        migrations.AddIndex(
            model_name='countryassignment',
            index=models.Index(fields=['committee', 'is_active'], name='committees__committ_bf6263_idx'),
        ),
        migrations.AddConstraint(
            model_name='countryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('committee', 'country_code'), name='unique_active_country_per_committee'),
        ),
    ]
