# Generated by Django 6.1 on 2026-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='committee_type',
            field=models.CharField(choices=[('general_assembly', 'General Assembly'), ('security_council', 'Security Council'), ('ecosoc', 'ECOSOC'), ('crisis', 'Crisis Committee'), ('specialized_agency', 'Specialized Agency'), ('indian_parliament', 'Indian Parliament'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
