# Generated by Django 6.1 on 2026-08-17 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chit_number', models.CharField(blank=True, editable=False, help_text='Human-readable chit number, e.g. MUN-2026-UNSC-000042', max_length=40, unique=True)),
                ('recipient_type', models.CharField(choices=[('delegate', 'Delegate'), ('executive_board', 'Executive Board'), ('administrator', 'Administrator')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('point_of_information', 'Point of Information'), ('procedural_question', 'Procedural Question'), ('motion_related', 'Motion Related'), ('clarification', 'Clarification'), ('bilateral_communication', 'Bilateral Communication'), ('other', 'Other')], default='other', max_length=32)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('delivered', 'Delivered'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=12)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chits', to='committees.committee')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chits', to='conferences.conference')),
                ('recipient', models.ForeignKey(blank=True, help_text='Set for direct EB/Administrator targeting; may be null for shared EB inbox.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chits', to=settings.AUTH_USER_MODEL)),
                ('recipient_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_country_chits', to='committees.countryassignment')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chits', to='conferences.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chits', to=settings.AUTH_USER_MODEL)),
                ('sender_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chits', to='committees.countryassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChitReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chit_replies', to=settings.AUTH_USER_MODEL)),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chits.chit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['committee'], name='chits_chit_committ_11e074_idx'),
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['room'], name='chits_chit_room_id_3a2c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['sender'], name='chits_chit_sender__aba8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['recipient'], name='chits_chit_recipie_808180_idx'),
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['status'], name='chits_chit_status_744199_idx'),
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['priority'], name='chits_chit_priorit_6060fa_idx'),
        ),
        migrations.AddIndex(
            model_name='chit',
            index=models.Index(fields=['created_at'], name='chits_chit_created_1c9c5b_idx'),
        ),
    ]
